[package]
name = "batadase"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
rkyv = "0.7"
grd-utils = "0.1"
enumflags2 = "0.7"
fehler = "1"
tracing = "0.1"
tokio = { version = "1", features = ["full"] }
lmdb-sys = { git = "ssh://git@github.com/GRDigital/lmdb-sys.git", rev = "87514c6" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
shrinkwraprs = "0.3"
thiserror = "1"
error = { path = "../error" }
libc = "0.2"
hobo = { version = "0.3", optional = true }
inspect = { path = "../inspect", optional = true }

[features]
inspect_control = ["hobo", "inspect"]
