[package]
name = "batadase"
version = "1.0.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/GRDigital/batadase"
description = "batadase is an incredible LMDB wrapper"
authors = ["GR Digital <contact@grdigital.co.uk>"]
readme = "README.md"

[dependencies]
anyhow = "1"
enumflags2 = "0.7"
fehler = "1"
libc = "0.2"
lmdb-sys = "0.11"
once_cell = "1"
rkyv = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
shrinkwraprs = "0.3"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
batadase-index = "1"
batadase-macros = "1"
semver = "1"
futures = "0.3"
log = "0.4"

[patch.crates-io]
lmdb-sys = { git = "ssh://git@github.com/GRDigital/lmdb-sys.git", rev = "87514c6" }
batadase-index = { path = "index" }
batadase-macros = { path = "macros" }
