[package]
name = "batadase"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
enumflags2 = "0.7"
fehler = "1"
libc = "0.2"
lmdb-sys = { git = "ssh://git@github.com/GRDigital/lmdb-sys.git", rev = "87514c6" }
rkyv = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
shrinkwraprs = "0.3"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
batadase-index = "1"
batadase-macros = "1"
semver = "1"
futures = "0.3"
log = "0.4"
